### ISSUE TITLE
allow setting environmental variables and resetting it after finished executaion with a call

### ISSUE THREAD

**Issue by cordoval** [bldr-io/bldr#113]
```
prodInstall:
            description: runs composer install with SYMFONY_ENV=prod
            calls:
                -
                    type: exec
                    executable: composer
                    failOnError: true
                    arguments:
                        - install
                        - --no-dev
```

I want to execute like in the shell SYMFONY_ENV=prod composer install --no-dev and then remove the SYMFONY_ENV var. Right now i cannot find any way for doing this.

I cannot set the env var permanently because i am just emulating the deploy on local but just setting the prod environment temporarily.
