### ISSUE TITLE
Running docker-composer command shows no output

### ISSUE THREAD

**Issue by AlexKovalevych** [bldr-io/bldr#148]
having a job:

```yml
        tests:
            description: Run tests
            tasks:
                -
                    type: exec
                    executable: docker-compose
                    arguments:
                        - run
                        - data
                        - "bin/phpunit -c app"
```

Running it:

```bash
./bldr.phar run test

 Using the 'test' profile
  - Run tests -

Running the tests job > Run tests

    [exec] - Starting

  Build Success!
```
Would be nice to see tests output here. If i run docker-compose directly in the shell i get all output:

```bash
➜  ✗ docker-compose run data "bin/phpunit -c app --coverage-html app/coverage"
PHPUnit 4.8.9 by Sebastian Bergmann and contributors.
Warning:	No whitelist configured for code coverage

................................................................. 65 / 80 ( 81%)
...............

Time: 28.26 seconds, Memory: 36.25Mb

```

Any ideas?
