### ISSUE TITLE
[Fix] - 2 watchers simultaneously

### ISSUE THREAD

**Issue by Padam87** [bldr-io/bldr#42]
Hi,

I've tried to use 2 watchers simultaneously, without much success. Is there any way to do this?

Thanks!

```
bldr:
    name: Test
    profiles:
        dev:
            description: Development
            tasks:
                - fosJSRouting
                - assetic
                - watch
    tasks:
        fosJSRouting:
            description: Dumps the routing
            calls:
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments:
                        - app/console
                        - fos:js-routing:dump
        assetic:
            description: Dumps assets
            calls:
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments:
                        - app/console
                        - assetic:dump
                        - --force
        watch:
            calls:
                -
                    type: watch
                    src:
                        - { path: [app/cache/dev], files: appDevUrlGenerator.php }
                    task: fosJSRouting
                -
                    type: watch
                    src:
                        - { path: web, files: [*.js, *.css, *.less], recursive: true }
                    task: assetic
```
